[package]
name = "druid-icon"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
build = "build.rs"

[dependencies]
druid = "0.8.2"

[build-dependencies]
winres = "0.1.12"